### PR TITLE
Allow user to configure maximum number of chips to display

### LINKED ISSUE #140: Feature request: Configure the number of selected chips to display
I have a feature request to allow users to specify the maximum number of chips that can be displayed in the dropdown. Once the selected options reach that limit we can show `More...` text and on clicking that we can show all the selected options with `Less...` text just before the search box. On clicking `Less...` it will again show the number of chips specified by the user. 

Furthermore, users can specify the text/component that should be shown in place of `More...` and `Less...`.

Please let me know what you think about this feature.

Below is a GIF showing how it can work. (Example is configured to show maximum of **2** selected options)

showmoreless

### PR DESCRIPTION
**Pull request by priyanshu92**
Fixes #140 

Allows user to configure how many selected chips to display. Also, gives them a way to pass the text or component to show when the selected chips reach that threshold. Default text is `More...` and `Less...`. Clicking on `More...` will expand the dropdown and show all the selected chips and clicking on `Less...` will again shirk the dropdown to show the maximum number of chips configured. 

New Props added:
--------------------
* `numberOfChipsToDisplay`: A number to configure the maximum number of chips to show.
* `showMore`: Text/Component to show if the selected options are more than the configured number. Defaults to `More...`.
* `showLess`: Text/Component to show if the dropdown is expanded to show all the options. Clicking this will only show that many chips which are configured in `numberOfChipsToDisplay`. Defaults to `Less...`

Note: This functionality will only work if  `numberOfChipsToDisplay` prop is used.

### CODE REVIEW

**Comment by mrchief** [comment]
Need to add tests. Also, if we could use sane defaults, that should reduce the number of if-else branches in the code.

**Comment by mrchief** [comment]
To better manage releases, I created a `develop` branch which will be the default branch going forward. `master` will be the stable, production branch. 

When you get a chance, can you change this PR's target branch to develop?

**Comment by priyanshu92** [comment]
Yep sure. I'll update it as soon as I get time to work on this.

**Comment by mrchief** [comment]
Don't mind the bot. Let me know when you're ready and I'll reopen this.

**Pull request closed without merging**
