### PR TITLE
feat: Add prop to skip navigation on nodes

### PR DESCRIPTION
**Pull request by isuscbrmid**
## What does it do?

Currently if I want to hide a node, I can do this with css, but the keyboard feature is able to reach those nodes. We cannot use the "hide" prop in each node, since it is overwritten when "restoringDefaults".

## Fixes # (issue)

Add a custom/optional prop to the nodes to disable keyboard navigation on them.

## Type of change

Please delete options that are not relevant.
- [x] New feature (non-breaking change which adds functionality)
- [x] This change requires a documentation update

# Checklist:

- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [x] Updated documentation (if applicable)
- [x] Added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] My changes generate no new warnings

### CODE REVIEW

**Comment by mrchief** [comment]
I don't think we need a new prop for this. Skipping all keyboard actions on hidden nodes can be the default behavior.

@ellinge Any apparent concerns if we do this?

**Comment by mrchief** [comment]
Also, please add tests for these changes.

**Comment by isuscbrmid** [comment]
> Also, please add tests for these changes.

no sure if I understand, more tests using that prop?

**Comment by isuscbrmid** [comment]
> I don't think we need a new prop for this. Skipping all keyboard actions on hidden nodes can be the default behavior.
> 
> @ellinge Any apparent concerns if we do this?

we need that because on https://github.com/dowjones/react-dropdown-tree-select/blob/02491b516efc00aa84e377e4ed87b7ac6acfe786/src/tree-manager/index.js#L125 we set the wholes nodes to false. So "hidden prop" will not work

**Comment by MJRuskin** [comment]
@isuscbrmid would you be ok with something like this #371 ?

Any nodes that were initially hidden in the data will remain hidden (and skipped by the keyboard navigation).
They only show up during search.

Unless of course you want a completely hidden "fake" node, and then you can label it "" which makes it is also unsearchable.

**Comment by mrchief** [comment]
> We cannot use the "hide" prop in each node, since it is overwritten when "restoringDefaults".

Not sure I understand this bit. 

In general, I'm usually hesitant to add more props like these ones as it increases the maintenance area in general while it provides little value to only a handful of edge cases. 

You also have to analyse the impact of this change from an accessibility standpoint. 

Also, can we have a CodeSandbox to reproduce the problem?

**Comment by isuscbrmid** [comment]
Sure i will send you the sandbox tomorowEl 25 may. 2020 9:37 p. m., Hrusikesh Panda <notifications@github.com> escribió:

We cannot use the "hide" prop in each node, since it is overwritten when "restoringDefaults".

Not sure I understand this bit.
In general, I'm usually hesitant to add more props like these ones as it increases the maintenance area in general while it provides little value to only a handful of edge cases.
You also have to analyse the impact of this change from an accessibility standpoint.
Also, can we have a CodeSandbox to reproduce the problem?

**Comment by isuscbrmid** [comment]
> #371

yes it seems it can be the solution, I will double check if this one work, will close my Pr

**Comment by mrchief** [comment]
> We cannot use the "hide" prop in each node, since it is overwritten when "restoringDefaults".

I guess I'm confused because there is no such prop; or a method called `restoringDefaults`.

**Comment by isuscbrmid** [comment]
sorry i write down wrongly the name, here the hidde is set to false, even if we pass a hidde = true at the beginning.. So only in the beginning it will hidde the node, but after closing the dropdown this method is triggered removing the hidde = true
https://github.com/dowjones/react-dropdown-tree-select/blob/02491b516efc00aa84e377e4ed87b7ac6acfe786/src/tree-manager/index.js#L123

**Comment by isuscbrmid** [comment]
I wil test @MJRuskin  PR I thing the way he did avoid that overwrite can help me

**Comment by isuscbrmid** [comment]
@mrchief we can close this.. The solution provided by @MJRuskin will work It avoid overwriting the default nodes hide prop when restoring nodes.

**Pull request closed without merging**
