### PR TITLE
feat: Support placeholder for inline search input

### LINKED ISSUE #388: Support for different texts for the dropdown and inline search input?
**Is your feature request related to a problem? Please describe.**

Support for different texts for the dropdown and inline search input.

Wanted UX:
Screen Shot 2020-06-30 at 9 40 45 AM

Implementation:
Screen Shot 2020-06-30 at 9 40 36 AM

**Describe the solution you'd like**

```
const texts = {
      placeholder: 'Select...',  // optional: The text to display as placeholder on the dropdown box. Defaults to `Choose...`
      placeholderInlineSearch: 'Search...',  // optional: The text to display as placeholder on the inline search box. Only applies to `inlineSearchInput`. Defaults to `Search...`
      noMatches: 'nope',    // optional: The text to display when the search does not find results in the content list. Defaults to `No matches found`
      label: '',        // optional: Adds `aria-labelledby` to search input when input starts with `#`, adds `aria-label` to search input when label has value (not containing '#')
      labelRemove: '',  // optional: The text to display for `aria-label` on tag delete buttons which is combined with `aria-labelledby` pointing to the node label. Defaults to `Remove`
    }
```

**Describe alternatives you've considered**

**Additional context**

### PR DESCRIPTION
**Pull request by ldeveber**
## What does it do?

Adds option `texts.inlineSearchPlaceholder` to customize the placeholder text for the inline search input

Screen Shot 2020-07-28 at 12 23 04 PM

## Fixes # (issue)

Closes #388 

## Type of change

Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds functionality)
- [x] This change requires a documentation update

# Checklist:

- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] Updated documentation (if applicable)
- [x] Added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] My changes generate no new warnings

### CODE REVIEW

**Comment by mrchief** [comment]
@ldeveber I'm wondering if we can do this without adding one more option. What if we hide the original placeholder when inline option is set? What's the point of having 2 placeholders?

**Comment by ldeveber** [comment]
> @ldeveber I'm wondering if we can do this without adding one more option. What if we hide the original placeholder when inline option is set? What's the point of having 2 placeholders?

Because the UX I need to support is:
Screen Shot 2020-08-10 at 11 26 51 AM
where it needs to say "Select a field..." and "Search"

**Comment by ldeveber** [comment]
> > @ldeveber I'm wondering if we can do this without adding one more option. What if we hide the original placeholder when inline option is set? What's the point of having 2 placeholders?
> 
> @mrchief Because the UX I need to support is:
> Screen Shot 2020-08-10 at 11 26 51 AM
> where it needs to say "Select a field..." and "Search"

@mrchief bump :(

**Comment by mrchief** [comment]
@ldeveber It hasn't dropped from my radar. Things have been busy lately but I have been going thru options to see if there's something more we can do.

**Comment by ldeveber** [comment]
> @ldeveber It hasn't dropped from my radar. Things have been busy lately but I have been going thru options to see if there's something more we can do.

@mrchief any updates?

**Comment by ldeveber** [comment]
> This issue has been automatically marked as stale because it has not had recent activity. It will be closed if no further activity occurs. Thank you for your contributions.

@mrchief any updates? :(

**Comment by mrchief** [comment]
@ldeveber sorry about the delay. The PR looks good. I'm thinking if it'd be helpful to add it to Options playground. 

image
 

You can add that under `docs/src/stories/Options` and the netlify status check will let you preview your branch changes.

image

**Comment by ldeveber** [comment]
> @ldeveber sorry about the delay. The PR looks good. I'm thinking if it'd be helpful to add it to Options playground.
> 
> image
> 
> You can add that under `docs/src/stories/Options` and the netlify status check will let you preview your branch changes.
> 
> image

Oh neat. I will update this :)

**Comment by ldeveber** [comment]
> @ldeveber sorry about the delay. The PR looks good. I'm thinking if it'd be helpful to add it to Options playground.

@mrchief All set! :)

Screen Shot 2020-09-24 at 10 46 18 AM

**Review by mrchief — APPROVED** [review]

**Comment by mrchief** [comment]
@ldeveber I see you added the option for placeholder text as well, thanks for that! This looks good! I'll try to get it out this weekend.

**Pull request merged**
