### PR TITLE
feat: Fast & efficient search rendering with large tree ✨

### LINKED ISSUE #80: Improve Search Performance with large number of nodes
Based on feedback from [here](https://github.com/dowjones/react-dropdown-tree-select/issues/77#issuecomment-379026487) and [here](https://github.com/dowjones/react-dropdown-tree-select/issues/79#issuecomment-379097943), need to improve search performance.

### PR DESCRIPTION
**Pull request by mrchief**
Fixes #80

### CODE REVIEW

**Comment by mrchief** [comment]
@josvegit Almost there. Just have to fix some prop type warnings during the demo but otherwise looks good.

**Comment by mrchief** [comment]
You can try pointing to this branch and see if it works for you. Help me beta test it :)

**Comment by josvegit** [comment]
Holy shit dude, thanks alot sorry for late answer, hade a bunch of GDPR related work..

**Comment by mrchief** [comment]
GDPR - that's easy right? :joy_cat:

**Comment by josvegit** [comment]
It's hard when companies have built in *misuse* of personal information into their systems :D

**Pull request merged**
