### PR TITLE
fix: Firefox outsideClick verification fails on certain elements (#148)

### PR DESCRIPTION
**Pull request by nikolap**
#148 partial fix. Now the tree display remains open, however scroll position is incorrectly reset

### CODE REVIEW

**Comment by nikolap** [comment]
Sure, send them along, more than happy to lend a hand if I can :)

**Comment by mrchief** [comment]
Ok so there are 2 ideas I wanted to explore. But before I lay out implementation details, here are the some of objectives I wanted to fulfill:

 - The outside click should be able to distinguish between multiple instances of the component on the same page. Basically improvise [this situation](https://github.com/dowjones/react-dropdown-tree-select/pull/139#discussion_r207079030) even when no unique classnames are passed.

 - The outside click should work on all browsers (including the less beloved IE). I'm OK with IE v11 and above if it comes to that.

 - If possible, do not involve any 3rd party libs (unless it's very very lean and introduces no significant increase in bundle size)

So with those golas in mind, what I wanted to try is:

 - [descendant check](https://github.com/dowjones/react-dropdown-tree-select/blob/bbd5c2ca62cb4f563dc49c8a7bcf680fa872370f/src/index.js#L89). We had this before but it wasn't working reliably. Don't remember why or how.  I think using `capture: true` on the document event listener might help. I'd also like to deregister the listeners on unmount and maybe play with onMouseDown/onMouseUp instead of onClick.

 - [invisible overlay](https://vncz.js.org/outsideclick/): this a neat trick that involves displaying a full screen modal with `z-index: -1` and listening for clicks on that div. The idea seems interesting and avoids global event handlers; but dealing with full screen modals is always tricky, especially with multiple components. Not to mention the caller app will most likely have its own modal overlays. 

I guess having an `OutsideClickHandler` that just takes a child component and deals with all the outside click handling might be better (rather than having it as part of `index.js` like I had above). 

So there you go. These are some of the ideas I had going. You're more than welcome to bring your own into the mix!

**Comment by nikolap** [comment]
Haven't played around with either approach yet, but another option I've seen is the way semantic UI react checks for clicks via appending a data-attribute to a ref:

https://github.com/Semantic-Org/Semantic-UI-React/blob/master/src/lib/doesNodeContainClick.js
https://github.com/Semantic-Org/Semantic-UI-React/blob/master/src/modules/Dropdown/Dropdown.js#L635

Let me know your thoughts...

**Comment by mrchief** [comment]
It's the same concept as descendant check but I'm not sure why it's so complex. Maybe they need to handle some use cases that require such logic.

But appending data-attribute seems like a moot op to me because we already have a ref node. Further, looking up by data-attribute will return all instances (basically same problem as non unique classname).

**Comment by nikolap** [comment]
Sorry, haven't had any chance to look into this recently. Feel free to go on without me. Otherwise, will have some time the following week or two

**Comment by nikolap** [comment]
Briefly looked at the previous approach via descendant check/Node.contains. The issue appears to be that the ref does not contain the updated dom information following the next call for InfiniteScroll. 

I think this may be tied to how the InfiniteScroll component manages state. Or perhaps how it's implemented here. If we resolve that it should hopefully a) let us use the Node.contains as  the check approach for outside click and b) prevent the scroll reset on FF and the scroll re-load on Chrome.

**Comment by mrchief** [comment]
Found a workaround for the time being: https://github.com/dowjones/react-dropdown-tree-select/commit/2a1302b9113805372131a0fd2386ed1831c87ae2. I tested on firefox and seems to be working. While this issue is definitely worth pursuing, we can release this fix to get you unblocked in the interim.

**Comment by nikolap** [comment]
Nice one! Thank you! I'll leave it to you to decide whether to release or not -- I can live with it for now while we look for a more permanent fix.

**Comment by mrchief** [comment]
Fixed via #177

**Pull request closed without merging**
