### PR TITLE
fix: action click node focus

### PR DESCRIPTION
**Pull request by isuscbrmid**
## What does it do?
When clicking a node on the action section, it is not focused or still focuses on the previous one. This is confusing.

## What this PR do?
Update the tree manager with the current node where the action was clicked with the _focused correct value.

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)

# Checklist:

- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] Updated documentation (if applicable)
- [x] Added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes 
Note: I had to update one of the tests since the returned node on the callback has the _focused value.
- [ ] My changes generate no new warnings

### CODE REVIEW

**Comment by mrchief** [comment]
Will you able able to paste a gif or screenshots? I want to see this "awkwardness". Action items were never meant to focus the nodes. You'd place the focus on the action item itself if you think about web accessibility standards since you're clicking a button/link (action item).

**Comment by isuscbrmid** [comment]
On my keyboard version, we focused the checkbox, and not the whole node. 

Since it is focusing on the whole node lists. It can be confusing to not see the node "focused" when I do some action there.

**Comment by isuscbrmid** [comment]
action-button

**Comment by isuscbrmid** [comment]
Screen Shot 2020-06-08 at 12 00 36
This is "focused", don't know why on the gif is not colored.

**Comment by mrchief** [comment]
You can add a hover or active CSS to achieve the highlight, no?

**Comment by isuscbrmid** [comment]
Yeah, but how we can remove that highlight, it will affect the styles when using keyboard actions. I think a good approach is to focus the node internally since if I start to use the keyboard you can start from the latest nodes with an interaction.

**Comment by mrchief** [comment]
Keyboard should be already highlighting items as you navigate. Actions is not the same as selecting a node. But I want to hear what others think. I'm kinda on the fence on this one. 

@ellinge @Gregcop1 @MJRuskin thoughts?

**Comment by mrchief** [comment]
not stale

**Pull request closed without merging**
